### ISSUE TITLE
Cannot generate output while pasting the QA results from excel sheet

### ISSUE THREAD

**Issue by SaurabhthePSI** [WDCryer/QA_Formatter_Website#12]
Hello,

I am facing certain issue in QA formatter.When I copy the QA results from Excel and paste it in the QA formatter, it doesn't give me any output. I wonder what might have happened to it that it's not giving me any output. Due to this my work is really suffering as I cannot reply back to the client with the QA results. Any help or advice would be of much help as I am really looking out for a solution to this.Hoping to hear back from you soon. To further clarify,Please find attached screenshot of the error that I am facing.

Thanks and Regards,
![qa_formatter_issue](https://cloud.githubusercontent.com/assets/17833606/13753279/4f20fa40-ea38-11e5-8cff-f4ac13c66f90.jpg)

Saurabh

**Comment by WDCryer** [comment]
Fixed.
